### ISSUE TITLE
unable to build under linux

### ISSUE THREAD

**Issue by ghost** [fabiensanglard/Shmup#2]
I tried to compile on linux (Ubuntu 12.04 LTS), but I got a lot compilation error, mostly about the png code and openal link error.

Maybe the makefile only work on specific debian version?
